

default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Twiit_app_development

  
test:
  <<: *default
  database: Twiit_app_test


production:
  <<: *default
  database: Twiit_app_production
  username: Twiit_app
  password: <%= ENV['TWIIT_APP_DATABASE_PASSWORD'] %>
